// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: admin.sql

package database

import (
	"context"
	"database/sql"
)

const create_HR_Admin = `-- name: Create_HR_Admin :execresult
INSERT INTO HR_Admin ( Name, Email, Role ) VALUES (?, ?, ?)
`

type Create_HR_AdminParams struct {
	Name  string `json:"name"`
	Email string `json:"email"`
	Role  string `json:"role"`
}

func (q *Queries) Create_HR_Admin(ctx context.Context, arg Create_HR_AdminParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, create_HR_Admin, arg.Name, arg.Email, arg.Role)
}
