// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: emp_confirmation.sql

package database

import (
	"context"
	"database/sql"
)

const createConfirmation = `-- name: CreateConfirmation :exec
INSERT INTO emp_confirmation_letter_table(emp_id) VALUES (
    ?
)
`

func (q *Queries) CreateConfirmation(ctx context.Context, empID int64) error {
	_, err := q.db.ExecContext(ctx, createConfirmation, empID)
	return err
}

const deleteConfirmation = `-- name: DeleteConfirmation :exec
DELETE FROM emp_confirmation_letter_table WHERE id = ?
`

func (q *Queries) DeleteConfirmation(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteConfirmation, id)
	return err
}

const getConfirmation = `-- name: GetConfirmation :many
SELECT 
    c.id,
    c.emp_id,
    CONCAT(e.file_name, " " ,e.last_name) AS name,
    c.created_at
FROM emp_confirmation_letter_table c
JOIN HR_Employee e ON c.emp_id = e.id
WHERE 
    (? = '' OR e.first_name LIKE CONCAT('%',?,'%'))
    AND(? = '' OR e.last_name LIKE CONCAT('%', ? ,'%')) 
LIMIT ? OFFSET ?
`

type GetConfirmationParams struct {
	Column1  interface{} `json:"column_1"`
	CONCAT   interface{} `json:"CONCAT"`
	Column3  interface{} `json:"column_3"`
	CONCAT_2 interface{} `json:"CONCAT_2"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

type GetConfirmationRow struct {
	ID        int64        `json:"id"`
	EmpID     int64        `json:"emp_id"`
	Name      string       `json:"name"`
	CreatedAt sql.NullTime `json:"created_at"`
}

func (q *Queries) GetConfirmation(ctx context.Context, arg GetConfirmationParams) ([]GetConfirmationRow, error) {
	rows, err := q.db.QueryContext(ctx, getConfirmation,
		arg.Column1,
		arg.CONCAT,
		arg.Column3,
		arg.CONCAT_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetConfirmationRow
	for rows.Next() {
		var i GetConfirmationRow
		if err := rows.Scan(
			&i.ID,
			&i.EmpID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
