// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: empLink.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const createEmpLink = `-- name: CreateEmpLink :exec
INSERT INTO emp_link (emp_data, preset_id, is_approved, email, updated_by) VALUES (?, ?, ?, ?, ?)
`

type CreateEmpLinkParams struct {
	EmpData    json.RawMessage `json:"emp_data"`
	PresetID   int64           `json:"preset_id"`
	IsApproved bool            `json:"is_approved"`
	Email      string          `json:"email"`
	UpdatedBy  sql.NullInt64   `json:"updated_by"`
}

func (q *Queries) CreateEmpLink(ctx context.Context, arg CreateEmpLinkParams) error {
	_, err := q.db.ExecContext(ctx, createEmpLink,
		arg.EmpData,
		arg.PresetID,
		arg.IsApproved,
		arg.Email,
		arg.UpdatedBy,
	)
	return err
}

const getEmpLinkByID = `-- name: GetEmpLinkByID :one
SELECT id, emp_data, preset_id, is_approved, create_date, email, updated_by FROM emp_link WHERE id = ?
`

func (q *Queries) GetEmpLinkByID(ctx context.Context, id int64) (EmpLink, error) {
	row := q.db.QueryRowContext(ctx, getEmpLinkByID, id)
	var i EmpLink
	err := row.Scan(
		&i.ID,
		&i.EmpData,
		&i.PresetID,
		&i.IsApproved,
		&i.CreateDate,
		&i.Email,
		&i.UpdatedBy,
	)
	return i, err
}

const getEmpLinkData = `-- name: GetEmpLinkData :one
SELECT 
    el.id AS emp_link_id,
    el.emp_data,
    el.is_approved,
    el.create_date,
    el.updated_by,
    el.email,
    ap.id AS preset_id,
    ap.preset_name,
    ap.preset_value,
    ap.slug
FROM emp_link el
JOIN Admin_Presets ap ON el.preset_id = ap.id
WHERE el.id = ?
`

type GetEmpLinkDataRow struct {
	EmpLinkID   int64           `json:"emp_link_id"`
	EmpData     json.RawMessage `json:"emp_data"`
	IsApproved  bool            `json:"is_approved"`
	CreateDate  time.Time       `json:"create_date"`
	UpdatedBy   sql.NullInt64   `json:"updated_by"`
	Email       string          `json:"email"`
	PresetID    int64           `json:"preset_id"`
	PresetName  string          `json:"preset_name"`
	PresetValue json.RawMessage `json:"preset_value"`
	Slug        string          `json:"slug"`
}

func (q *Queries) GetEmpLinkData(ctx context.Context, id int64) (GetEmpLinkDataRow, error) {
	row := q.db.QueryRowContext(ctx, getEmpLinkData, id)
	var i GetEmpLinkDataRow
	err := row.Scan(
		&i.EmpLinkID,
		&i.EmpData,
		&i.IsApproved,
		&i.CreateDate,
		&i.UpdatedBy,
		&i.Email,
		&i.PresetID,
		&i.PresetName,
		&i.PresetValue,
		&i.Slug,
	)
	return i, err
}

const listEmpLinks = `-- name: ListEmpLinks :many
SELECT id, emp_data, preset_id, is_approved, create_date, email, updated_by FROM emp_link
`

func (q *Queries) ListEmpLinks(ctx context.Context) ([]EmpLink, error) {
	rows, err := q.db.QueryContext(ctx, listEmpLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmpLink
	for rows.Next() {
		var i EmpLink
		if err := rows.Scan(
			&i.ID,
			&i.EmpData,
			&i.PresetID,
			&i.IsApproved,
			&i.CreateDate,
			&i.Email,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmpLinkApproval = `-- name: UpdateEmpLinkApproval :exec
UPDATE emp_link SET is_approved = 1, updated_by = ? WHERE id = ?
`

type UpdateEmpLinkApprovalParams struct {
	UpdatedBy sql.NullInt64 `json:"updated_by"`
	ID        int64         `json:"id"`
}

func (q *Queries) UpdateEmpLinkApproval(ctx context.Context, arg UpdateEmpLinkApprovalParams) error {
	_, err := q.db.ExecContext(ctx, updateEmpLinkApproval, arg.UpdatedBy, arg.ID)
	return err
}
