// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: exchangerate.sql

package database

import (
	"context"
	"database/sql"

	"github.com/shopspring/decimal"
)

const createExchangeRate = `-- name: CreateExchangeRate :exec
INSERT INTO Exchange_Rate (exchange_rate, currency_type)
VALUES (?, ?)
`

type CreateExchangeRateParams struct {
	ExchangeRate decimal.Decimal `json:"exchange_rate"`
	CurrencyType string          `json:"currency_type"`
}

func (q *Queries) CreateExchangeRate(ctx context.Context, arg CreateExchangeRateParams) error {
	_, err := q.db.ExecContext(ctx, createExchangeRate, arg.ExchangeRate, arg.CurrencyType)
	return err
}

const deleteExchangeRate = `-- name: DeleteExchangeRate :exec
DELETE FROM Exchange_Rate
WHERE id = ?
`

func (q *Queries) DeleteExchangeRate(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteExchangeRate, id)
	return err
}

const getExchangeRateAll = `-- name: GetExchangeRateAll :many
SELECT exchange_rate, id, currency_type, created_at
FROM Exchange_Rate
ORDER BY created_at DESC
`

type GetExchangeRateAllRow struct {
	ExchangeRate decimal.Decimal `json:"exchange_rate"`
	ID           int64           `json:"id"`
	CurrencyType string          `json:"currency_type"`
	CreatedAt    sql.NullTime    `json:"created_at"`
}

func (q *Queries) GetExchangeRateAll(ctx context.Context) ([]GetExchangeRateAllRow, error) {
	rows, err := q.db.QueryContext(ctx, getExchangeRateAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExchangeRateAllRow
	for rows.Next() {
		var i GetExchangeRateAllRow
		if err := rows.Scan(
			&i.ExchangeRate,
			&i.ID,
			&i.CurrencyType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExhangeRateById = `-- name: GetExhangeRateById :one
SELECT exchange_rate, currency_type
FROM Exchange_Rate
WHERE id = ?
`

type GetExhangeRateByIdRow struct {
	ExchangeRate decimal.Decimal `json:"exchange_rate"`
	CurrencyType string          `json:"currency_type"`
}

func (q *Queries) GetExhangeRateById(ctx context.Context, id int64) (GetExhangeRateByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getExhangeRateById, id)
	var i GetExhangeRateByIdRow
	err := row.Scan(&i.ExchangeRate, &i.CurrencyType)
	return i, err
}

const getLatestExchangeRate = `-- name: GetLatestExchangeRate :many
SELECT exchange_rate, id, created_at
FROM Exchange_Rate
WHERE currency_type = ?
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestExchangeRateRow struct {
	ExchangeRate decimal.Decimal `json:"exchange_rate"`
	ID           int64           `json:"id"`
	CreatedAt    sql.NullTime    `json:"created_at"`
}

func (q *Queries) GetLatestExchangeRate(ctx context.Context, currencyType string) ([]GetLatestExchangeRateRow, error) {
	rows, err := q.db.QueryContext(ctx, getLatestExchangeRate, currencyType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLatestExchangeRateRow
	for rows.Next() {
		var i GetLatestExchangeRateRow
		if err := rows.Scan(&i.ExchangeRate, &i.ID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
