// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/shopspring/decimal"
)

type EmpAirticketReqStatus string

const (
	EmpAirticketReqStatusPending  EmpAirticketReqStatus = "pending"
	EmpAirticketReqStatusApproved EmpAirticketReqStatus = "approved"
	EmpAirticketReqStatusRejected EmpAirticketReqStatus = "rejected"
)

func (e *EmpAirticketReqStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EmpAirticketReqStatus(s)
	case string:
		*e = EmpAirticketReqStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for EmpAirticketReqStatus: %T", src)
	}
	return nil
}

type NullEmpAirticketReqStatus struct {
	EmpAirticketReqStatus EmpAirticketReqStatus `json:"emp_airticket_req_status"`
	Valid                 bool                  `json:"valid"` // Valid is true if EmpAirticketReqStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEmpAirticketReqStatus) Scan(value interface{}) error {
	if value == nil {
		ns.EmpAirticketReqStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EmpAirticketReqStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEmpAirticketReqStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EmpAirticketReqStatus), nil
}

type HrEmpAttendanceAttendanceType string

const (
	HrEmpAttendanceAttendanceTypeIn  HrEmpAttendanceAttendanceType = "in"
	HrEmpAttendanceAttendanceTypeOut HrEmpAttendanceAttendanceType = "out"
)

func (e *HrEmpAttendanceAttendanceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = HrEmpAttendanceAttendanceType(s)
	case string:
		*e = HrEmpAttendanceAttendanceType(s)
	default:
		return fmt.Errorf("unsupported scan type for HrEmpAttendanceAttendanceType: %T", src)
	}
	return nil
}

type NullHrEmpAttendanceAttendanceType struct {
	HrEmpAttendanceAttendanceType HrEmpAttendanceAttendanceType `json:"hr_emp_attendance_attendance_type"`
	Valid                         bool                          `json:"valid"` // Valid is true if HrEmpAttendanceAttendanceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullHrEmpAttendanceAttendanceType) Scan(value interface{}) error {
	if value == nil {
		ns.HrEmpAttendanceAttendanceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.HrEmpAttendanceAttendanceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullHrEmpAttendanceAttendanceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.HrEmpAttendanceAttendanceType), nil
}

type AdminPreset struct {
	ID          int64           `json:"id"`
	PresetName  string          `json:"preset_name"`
	PresetValue json.RawMessage `json:"preset_value"`
	Slug        string          `json:"slug"`
}

type DoorLockUser struct {
	AttendeeID     int64          `json:"attendee_id"`
	UserID         int64          `json:"user_id"`
	BranchID       int64          `json:"branch_id"`
	SubscriptionID sql.NullInt64  `json:"subscription_id"`
	LastIn         sql.NullTime   `json:"last_in"`
	LastOut        sql.NullTime   `json:"last_out"`
	CurrentState   sql.NullString `json:"current_state"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
	Username       string         `json:"username"`
	Email          sql.NullString `json:"email"`
	Role           sql.NullString `json:"role"`
	Phone          sql.NullString `json:"phone"`
	Nic            sql.NullString `json:"nic"`
	AvatarUrl      sql.NullString `json:"avatar_url"`
}

type EmpAirticketReq struct {
	ID             int64                 `json:"id"`
	PassengerName  string                `json:"passenger_name"`
	PassengerEmail string                `json:"passenger_email"`
	PassportNumber string                `json:"passport_number"`
	DepartureDate  time.Time             `json:"departure_date"`
	ReturnDate     time.Time             `json:"return_date"`
	DepartureCity  string                `json:"departure_city"`
	ArrivalCity    string                `json:"arrival_city"`
	Reason         string                `json:"reason"`
	EmpID          int64                 `json:"emp_id"`
	BranchID       int64                 `json:"branch_id"`
	Status         EmpAirticketReqStatus `json:"status"`
	CreatedAt      sql.NullTime          `json:"created_at"`
	UpdatedAt      sql.NullTime          `json:"updated_at"`
}

type EmpConfirmationLetterTable struct {
	ID        int64        `json:"id"`
	EmpID     int64        `json:"emp_id"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type EmpLink struct {
	ID         int64           `json:"id"`
	EmpData    json.RawMessage `json:"emp_data"`
	PresetID   int64           `json:"preset_id"`
	IsApproved bool            `json:"is_approved"`
	CreateDate time.Time       `json:"create_date"`
	Email      string          `json:"email"`
	UpdatedBy  sql.NullInt64   `json:"updated_by"`
}

type EmpLoanReq struct {
	ID                int64          `json:"id"`
	EmpID             int64          `json:"emp_id"`
	Reason            sql.NullString `json:"reason"`
	Amount            sql.NullString `json:"amount"`
	Status            sql.NullString `json:"status"`
	DeclinedBy        sql.NullInt64  `json:"declined_by"`
	DeclineReason     sql.NullString `json:"decline_reason"`
	RequestedDate     sql.NullTime   `json:"requested_date"`
	StatusChangedDate sql.NullTime   `json:"status_changed_date"`
}

type ExchangeRate struct {
	ID           int64           `json:"id"`
	ExchangeRate decimal.Decimal `json:"exchange_rate"`
	CurrencyType string          `json:"currency_type"`
	CreatedAt    sql.NullTime    `json:"created_at"`
	UpdatedAt    sql.NullTime    `json:"updated_at"`
}

type FlmTrainerAssign struct {
	ID        uint64       `json:"id"`
	TrainerID int64        `json:"trainer_id"`
	BranchID  int64        `json:"branch_id"`
	ClientID  int64        `json:"client_id"`
	FlmID     int64        `json:"flm_id"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	From      time.Time    `json:"from"`
	To        time.Time    `json:"to"`
}

type FlmUser struct {
	ID        int64        `json:"id"`
	Username  string       `json:"username"`
	BranchID  int64        `json:"branch_id"`
	Email     string       `json:"email"`
	Password  string       `json:"password"`
	Type      string       `json:"type"`
	Ban       bool         `json:"ban"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type HrAdmin struct {
	ID        int64         `json:"id"`
	UserName  string        `json:"user_name"`
	Email     string        `json:"email"`
	Password  string        `json:"password"`
	Role      string        `json:"role"`
	Status    string        `json:"status"`
	BranchID  int64         `json:"branch_id"`
	CreatedBy sql.NullInt64 `json:"created_by"`
	UpdatedBy sql.NullInt64 `json:"updated_by"`
	CreatedAt sql.NullTime  `json:"created_at"`
	UpdatedAt sql.NullTime  `json:"updated_at"`
}

type HrBranch struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type HrCreateAllowance struct {
	ID            int64           `json:"id"`
	AllowanceType string          `json:"allowance_type"`
	Amount        decimal.Decimal `json:"amount"`
	UpdatedBy     sql.NullInt64   `json:"updated_by"`
	CreatedAt     sql.NullTime    `json:"created_at"`
	UpdatedAt     sql.NullTime    `json:"updated_at"`
}

type HrCreateService struct {
	ID        int64         `json:"id"`
	Category  string        `json:"category"`
	Value     string        `json:"value"`
	UpdatedBy sql.NullInt64 `json:"updated_by"`
	CreatedAt sql.NullTime  `json:"created_at"`
	UpdatedAt sql.NullTime  `json:"updated_at"`
}

type HrEmpAccessiability struct {
	ID                int64         `json:"id"`
	Accessibility     bool          `json:"accessibility"`
	AccessibilityFrom time.Time     `json:"accessibility_from"`
	AccessibilityTill time.Time     `json:"accessibility_till"`
	Enable            bool          `json:"enable"`
	UpdatedBy         sql.NullInt64 `json:"updated_by"`
	EmployeeID        int64         `json:"employee_id"`
	CreatedAt         sql.NullTime  `json:"created_at"`
	UpdatedAt         sql.NullTime  `json:"updated_at"`
}

type HrEmpAllowance struct {
	ID         int64           `json:"id"`
	Name       string          `json:"name"`
	Amount     decimal.Decimal `json:"amount"`
	UpdatedBy  sql.NullInt64   `json:"updated_by"`
	EmployeeID int64           `json:"employee_id"`
	CreatedAt  sql.NullTime    `json:"created_at"`
	UpdatedAt  sql.NullTime    `json:"updated_at"`
}

type HrEmpAttendance struct {
	ID             int64                         `json:"id"`
	EmpID          int64                         `json:"emp_id"`
	AttendanceType HrEmpAttendanceAttendanceType `json:"attendance_type"`
	CreateDate     time.Time                     `json:"create_date"`
}

type HrEmpBankDetail struct {
	ID            int64         `json:"id"`
	BankName      string        `json:"bank_name"`
	BranchName    string        `json:"branch_name"`
	AccountNumber string        `json:"account_number"`
	AccountHolder string        `json:"account_holder"`
	UpdatedBy     sql.NullInt64 `json:"updated_by"`
	EmployeeID    int64         `json:"employee_id"`
	CreatedAt     sql.NullTime  `json:"created_at"`
	UpdatedAt     sql.NullTime  `json:"updated_at"`
}

type HrEmpBenifit struct {
	ID                 int64          `json:"id"`
	LeaveStatus        bool           `json:"leave_status"`
	HealthInsurance    string         `json:"health_insurance"`
	InsuranceFrom      time.Time      `json:"insurance_from"`
	InsuranceTill      time.Time      `json:"insurance_till"`
	RetainmentPlan     string         `json:"retainment_plan"`
	RetainmentPlanFrom time.Time      `json:"retainment_plan_from"`
	RetainmentPlanTill time.Time      `json:"retainment_plan_till"`
	UpdatedBy          sql.NullInt64  `json:"updated_by"`
	EmployeeID         int64          `json:"employee_id"`
	CreatedAt          sql.NullTime   `json:"created_at"`
	UpdatedAt          sql.NullTime   `json:"updated_at"`
	LeaveType          sql.NullString `json:"leave_type"`
	LeaveCount         sql.NullInt32  `json:"leave_count"`
	Uniform            sql.NullBool   `json:"uniform"`
	UniformQuantity    sql.NullInt32  `json:"uniform_quantity"`
	UniformRenewMonths sql.NullInt32  `json:"uniform_renew_months"`
	Ticket             sql.NullBool   `json:"ticket"`
	TicketQuantity     sql.NullInt32  `json:"ticket_quantity"`
}

type HrEmpCertificate struct {
	ID         int64         `json:"id"`
	Date       time.Time     `json:"date"`
	Name       string        `json:"name"`
	UpdatedBy  sql.NullInt64 `json:"updated_by"`
	EmployeeID int64         `json:"employee_id"`
	CreatedAt  sql.NullTime  `json:"created_at"`
	UpdatedAt  sql.NullTime  `json:"updated_at"`
}

type HrEmpEmergencyDetail struct {
	ID           int64         `json:"id"`
	FirstName    string        `json:"first_name"`
	LastName     string        `json:"last_name"`
	Relationship string        `json:"relationship"`
	Contact      string        `json:"contact"`
	UpdatedBy    sql.NullInt64 `json:"updated_by"`
	EmployeeID   int64         `json:"employee_id"`
	CreatedAt    sql.NullTime  `json:"created_at"`
	UpdatedAt    sql.NullTime  `json:"updated_at"`
}

type HrEmpExpatriate struct {
	ID          int64           `json:"id"`
	Expatriate  bool            `json:"expatriate"`
	UpdatedBy   sql.NullInt64   `json:"updated_by"`
	EmployeeID  int64           `json:"employee_id"`
	CreatedAt   sql.NullTime    `json:"created_at"`
	UpdatedAt   sql.NullTime    `json:"updated_at"`
	Nationality sql.NullString  `json:"nationality"`
	VisaType    sql.NullString  `json:"visa_type"`
	VisaFrom    sql.NullTime    `json:"visa_from"`
	VisaTill    sql.NullTime    `json:"visa_till"`
	VisaNumber  sql.NullString  `json:"visa_number"`
	VisaFee     decimal.Decimal `json:"visa_fee"`
}

type HrEmpLeafe struct {
	ID         int64         `json:"id"`
	EmpID      int64         `json:"emp_id"`
	LeaveType  string        `json:"leave_type"`
	LeaveDate  time.Time     `json:"leave_date"`
	Reason     string        `json:"reason"`
	CreateDate sql.NullTime  `json:"create_date"`
	AddedBy    sql.NullInt64 `json:"added_by"`
}

type HrEmpSalary struct {
	ID                        int64           `json:"id"`
	SalaryType                string          `json:"salary_type"`
	Amount                    decimal.Decimal `json:"amount"`
	TotalOfSalaryAllowances   decimal.Decimal `json:"total_of_salary_allowances"`
	PensionEmployer           decimal.Decimal `json:"pension_employer"`
	PensionEmployee           decimal.Decimal `json:"pension_employee"`
	TotalNetSalary            decimal.Decimal `json:"total_net_salary"`
	UpdatedBy                 sql.NullInt64   `json:"updated_by"`
	EmployeeID                int64           `json:"employee_id"`
	CreatedAt                 sql.NullTime    `json:"created_at"`
	UpdatedAt                 sql.NullTime    `json:"updated_at"`
	ErID                      sql.NullInt64   `json:"er_id"`
	SalaryAmountType          string          `json:"salary_amount_type"`
	TotalSalaryAllowancesType string          `json:"total_salary_allowances_type"`
	PensionEmployerType       string          `json:"pension_employer_type"`
	PensionEmployeeType       string          `json:"pension_employee_type"`
	TotalNetSalaryType        string          `json:"total_net_salary_type"`
}

type HrEmpSchedual struct {
	ID    int64 `json:"id"`
	EmpID int64 `json:"emp_id"`
	// true = working day, false = off day
	Monday        sql.NullBool `json:"monday"`
	MondayFrom    sql.NullTime `json:"monday_from"`
	MondayTo      sql.NullTime `json:"monday_to"`
	Tuesday       sql.NullBool `json:"tuesday"`
	TuesdayFrom   sql.NullTime `json:"tuesday_from"`
	TuesdayTo     sql.NullTime `json:"tuesday_to"`
	Wednesday     sql.NullBool `json:"wednesday"`
	WednesdayFrom sql.NullTime `json:"wednesday_from"`
	WednesdayTo   sql.NullTime `json:"wednesday_to"`
	Thursday      sql.NullBool `json:"thursday"`
	ThursdayFrom  sql.NullTime `json:"thursday_from"`
	ThursdayTo    sql.NullTime `json:"thursday_to"`
	Friday        sql.NullBool `json:"friday"`
	FridayFrom    sql.NullTime `json:"friday_from"`
	FridayTo      sql.NullTime `json:"friday_to"`
	Saturday      sql.NullBool `json:"saturday"`
	SaturdayFrom  sql.NullTime `json:"saturday_from"`
	SaturdayTo    sql.NullTime `json:"saturday_to"`
	Sunday        sql.NullBool `json:"sunday"`
	SundayFrom    sql.NullTime `json:"sunday_from"`
	SundayTo      sql.NullTime `json:"sunday_to"`
	CreatedAt     sql.NullTime `json:"created_at"`
	UpdatedAt     sql.NullTime `json:"updated_at"`
}

type HrEmpSchedualAdditional struct {
	ID        int64        `json:"id"`
	EmpID     int64        `json:"emp_id"`
	Date      time.Time    `json:"date"`
	FromTime  sql.NullTime `json:"from_time"`
	ToTime    sql.NullTime `json:"to_time"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type HrEmpStatus struct {
	ID          int64         `json:"id"`
	Status      string        `json:"status"`
	Department  string        `json:"department"`
	Designation string        `json:"designation"`
	ValidFrom   time.Time     `json:"valid_from"`
	ValidTill   time.Time     `json:"valid_till"`
	UpdatedBy   sql.NullInt64 `json:"updated_by"`
	EmployeeID  int64         `json:"employee_id"`
	CreatedAt   sql.NullTime  `json:"created_at"`
	UpdatedAt   sql.NullTime  `json:"updated_at"`
}

type HrEmpUser struct {
	ID         int64         `json:"id"`
	Email      string        `json:"email"`
	Password   string        `json:"password"`
	UpdatedBy  sql.NullInt64 `json:"updated_by"`
	EmployeeID int64         `json:"employee_id"`
	BranchID   int64         `json:"branch_id"`
	CreatedAt  sql.NullTime  `json:"created_at"`
	UpdatedAt  sql.NullTime  `json:"updated_at"`
}

type HrEmployee struct {
	ID                int64         `json:"id"`
	FirstName         string        `json:"first_name"`
	LastName          string        `json:"last_name"`
	Gender            string        `json:"gender"`
	Dob               time.Time     `json:"dob"`
	Religion          string        `json:"religion"`
	PrimaryNumber     string        `json:"primary_number"`
	SecondaryNumber   string        `json:"secondary_number"`
	PassportID        string        `json:"passport_id"`
	Nationality       string        `json:"nationality"`
	PassportValidTill time.Time     `json:"passport_valid_till"`
	Nic               string        `json:"nic"`
	Country           string        `json:"country"`
	NicValidTill      time.Time     `json:"nic_valid_till"`
	Address           string        `json:"address"`
	CurrentCountry    string        `json:"current_country"`
	Email             string        `json:"email"`
	UpdatedBy         sql.NullInt64 `json:"updated_by"`
	CreatedAt         sql.NullTime  `json:"created_at"`
	UpdatedAt         sql.NullTime  `json:"updated_at"`
	IsBan             bool          `json:"is_ban"`
}

type HrFilesubmit struct {
	ID         int64        `json:"id"`
	EmployeeID int64        `json:"employee_id"`
	FileName   string       `json:"file_name"`
	FileType   string       `json:"file_type"`
	CreatedAt  sql.NullTime `json:"created_at"`
	UpdatedAt  sql.NullTime `json:"updated_at"`
}

type HrPayroll struct {
	ID                         int64           `json:"id"`
	Date                       time.Time       `json:"date"`
	SalaryType                 string          `json:"salary_type"`
	Amount                     decimal.Decimal `json:"amount"`
	TotalOfSalaryAllowances    decimal.Decimal `json:"total_of_salary_allowances"`
	Pension                    bool            `json:"pension"`
	PensionEmployer            sql.NullString  `json:"pension_employer"`
	PensionEmployee            sql.NullString  `json:"pension_employee"`
	TotalNetSalary             decimal.Decimal `json:"total_net_salary"`
	Tax                        bool            `json:"tax"`
	TaxPercentage              sql.NullString  `json:"tax_percentage"`
	TotalNetSalaryAfterTax     decimal.Decimal `json:"total_net_salary_after_tax"`
	UpdatedBy                  sql.NullInt64   `json:"updated_by"`
	CreatedAt                  sql.NullTime    `json:"created_at"`
	UpdatedAt                  sql.NullTime    `json:"updated_at"`
	SalaryAmountType           string          `json:"salary_amount_type"`
	TotalAllowancesType        string          `json:"total_allowances_type"`
	PensionEmployerType        sql.NullString  `json:"pension_employer_type"`
	PensionEmployeeType        sql.NullString  `json:"pension_employee_type"`
	TotalNetSalaryType         string          `json:"total_net_salary_type"`
	TotalNetSalaryAfterTaxType string          `json:"total_net_salary_after_tax_type"`
	ErID                       sql.NullInt64   `json:"er_id"`
	EmpID                      sql.NullInt64   `json:"emp_id"`
}

type HrPayrollAllowance struct {
	ID         int64           `json:"id"`
	Name       string          `json:"name"`
	Amount     decimal.Decimal `json:"amount"`
	PayrollID  int64           `json:"payroll_id"`
	UpdatedBy  sql.NullInt64   `json:"updated_by"`
	CreatedAt  sql.NullTime    `json:"created_at"`
	AmountType string          `json:"amount_type"`
}

type HrTax struct {
	ID            int64           `json:"id"`
	TaxFrom       decimal.Decimal `json:"tax_from"`
	TaxTo         decimal.Decimal `json:"tax_to"`
	TaxPercentage decimal.Decimal `json:"tax_percentage"`
	CreatedAt     sql.NullTime    `json:"created_at"`
	UpdatedBy     sql.NullInt64   `json:"updated_by"`
}

type HrTrainerCom struct {
	ID            int64           `json:"id"`
	PayrollID     int64           `json:"payroll_id"`
	TrainerID     int64           `json:"trainer_id"`
	EmployeeID    int64           `json:"employee_id"`
	Commission    decimal.Decimal `json:"commission"`
	AssignedCount int64           `json:"assigned_count"`
	Total         decimal.Decimal `json:"total"`
	CreatedAt     sql.NullTime    `json:"created_at"`
	UpdatedAt     sql.NullTime    `json:"updated_at"`
	UpdatedBy     sql.NullInt64   `json:"updated_by"`
}

type HrTrainerEmp struct {
	ID         int64           `json:"id"`
	TrainerID  int64           `json:"trainer_id"`
	EmployeeID int64           `json:"employee_id"`
	AttendeeID int64           `json:"attendee_id"`
	CreatedAt  sql.NullTime    `json:"created_at"`
	UpdatedAt  sql.NullTime    `json:"updated_at"`
	Commission decimal.Decimal `json:"commission"`
	UpdatedBy  sql.NullInt64   `json:"updated_by"`
}

type SessionWorkout struct {
	ID              int64          `json:"id"`
	PresetSessionID int64          `json:"preset_session_id"`
	ActiveDay       int64          `json:"active_day"`
	WorkoutID       int64          `json:"workout_id"`
	Status          sql.NullString `json:"status"`
	SessionID       int64          `json:"session_id"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
}

type V2preset struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	TrainerID   int64          `json:"trainer_id"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type V2presetSession struct {
	ID            int64        `json:"id"`
	PresetID      int64        `json:"preset_id"`
	ClientID      int64        `json:"client_id"`
	AssignSession int64        `json:"assign_session"`
	ActiveDay     int64        `json:"active_day"`
	MaxDay        int64        `json:"max_day"`
	State         string       `json:"state"`
	CreatedAt     sql.NullTime `json:"created_at"`
	UpdatedAt     sql.NullTime `json:"updated_at"`
}

type V2presetWorkout struct {
	ID        int64          `json:"id"`
	PresetID  int64          `json:"preset_id"`
	WorkoutID int64          `json:"workout_id"`
	Weight    sql.NullString `json:"weight"`
	Notes     sql.NullString `json:"notes"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
	Reps      int64          `json:"reps"`
	Sets      int64          `json:"sets"`
}

type V2session struct {
	ID        int64        `json:"id"`
	ClientID  int64        `json:"client_id"`
	TrainerID int64        `json:"trainer_id"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type Workout struct {
	ID                  int64          `json:"id"`
	Title               string         `json:"title"`
	Description         sql.NullString `json:"description"`
	AnimationUrl        sql.NullString `json:"animation_url"`
	PreviewAnimationUrl sql.NullString `json:"preview_animation_url"`
	Categories          sql.NullString `json:"categories"`
	Optional            sql.NullString `json:"optional"`
	CreatedAt           sql.NullTime   `json:"created_at"`
	UpdatedAt           sql.NullTime   `json:"updated_at"`
}
