// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"context"
	"database/sql"
	"time"
)

type Querier interface {
	AddHRBranch(ctx context.Context, name string) error
	AdminLogin(ctx context.Context, email string) (AdminLoginRow, error)
	CheckTrainerFromEmail(ctx context.Context, email sql.NullString) (CheckTrainerFromEmailRow, error)
	CreateAllowances(ctx context.Context, arg CreateAllowancesParams) error
	CreateEmpAccessiability(ctx context.Context, arg CreateEmpAccessiabilityParams) error
	CreateEmpAllowances(ctx context.Context, arg CreateEmpAllowancesParams) error
	CreateEmpBankDetails(ctx context.Context, arg CreateEmpBankDetailsParams) error
	CreateEmpBenifits(ctx context.Context, arg CreateEmpBenifitsParams) error
	CreateEmpCertificates(ctx context.Context, arg CreateEmpCertificatesParams) error
	CreateEmpEmergencyDetails(ctx context.Context, arg CreateEmpEmergencyDetailsParams) error
	CreateEmpExpatriate(ctx context.Context, arg CreateEmpExpatriateParams) error
	CreateEmpSalary(ctx context.Context, arg CreateEmpSalaryParams) error
	CreateEmpStatus(ctx context.Context, arg CreateEmpStatusParams) error
	CreateEmpUser(ctx context.Context, arg CreateEmpUserParams) error
	CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (sql.Result, error)
	CreateExchangeRate(ctx context.Context, arg CreateExchangeRateParams) error
	CreateFileSubmit(ctx context.Context, arg CreateFileSubmitParams) error
	CreateHRTrainerCom(ctx context.Context, arg CreateHRTrainerComParams) error
	CreateHrAdmin(ctx context.Context, arg CreateHrAdminParams) error
	CreatePayroll(ctx context.Context, arg CreatePayrollParams) (sql.Result, error)
	CreatePayrollAllowances(ctx context.Context, arg CreatePayrollAllowancesParams) error
	CreatePreset(ctx context.Context, arg CreatePresetParams) error
	CreatePresetSession(ctx context.Context, arg CreatePresetSessionParams) error
	CreatePresetWorkout(ctx context.Context, arg CreatePresetWorkoutParams) error
	CreateServices(ctx context.Context, arg CreateServicesParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateSessionWorkout(ctx context.Context, arg CreateSessionWorkoutParams) error
	CreateTax(ctx context.Context, arg CreateTaxParams) error
	CreateTrainerEmp(ctx context.Context, arg CreateTrainerEmpParams) error
	DeleteAllowance(ctx context.Context, id int64) error
	DeleteEmpAccessiability(ctx context.Context, employeeID int64) error
	DeleteEmpAllowances(ctx context.Context, employeeID int64) error
	DeleteEmpBankDetails(ctx context.Context, employeeID int64) error
	DeleteEmpBenifits(ctx context.Context, employeeID int64) error
	DeleteEmpCertificates(ctx context.Context, employeeID int64) error
	DeleteEmpEmergencyDetails(ctx context.Context, employeeID int64) error
	DeleteEmpExpatriate(ctx context.Context, employeeID int64) error
	DeleteEmpFiles(ctx context.Context, arg DeleteEmpFilesParams) error
	DeleteEmpSalary(ctx context.Context, employeeID int64) error
	DeleteEmpStatus(ctx context.Context, employeeID int64) error
	DeleteEmpUser(ctx context.Context, employeeID int64) error
	DeleteEmployee(ctx context.Context, id int64) error
	DeleteExchangeRate(ctx context.Context, id int64) error
	DeleteHrAdmin(ctx context.Context, id int64) error
	DeleteHrBranch(ctx context.Context, id int64) error
	DeletePreset(ctx context.Context, id int64) error
	DeletePresetSession(ctx context.Context, id int64) error
	DeletePresetWorkout(ctx context.Context, id int64) error
	DeleteService(ctx context.Context, id int64) error
	DeleteSession(ctx context.Context, id int64) error
	DeleteSessionWorkout(ctx context.Context, id int64) error
	DeleteTax(ctx context.Context, id int64) error
	EmployeeLogin(ctx context.Context, email string) (EmployeeLoginRow, error)
	GetAllHRBranch(ctx context.Context) ([]HrBranch, error)
	GetAllowance(ctx context.Context, id int64) (HrCreateAllowance, error)
	GetAllowances(ctx context.Context) ([]GetAllowancesRow, error)
	GetCertificateFile(ctx context.Context, employeeID int64) (string, error)
	GetEmpFiles(ctx context.Context, employeeID int64) ([]GetEmpFilesRow, error)
	GetEmployee(ctx context.Context, arg GetEmployeeParams) ([]GetEmployeeRow, error)
	GetEmployeeAllowances(ctx context.Context, employeeID int64) ([]GetEmployeeAllowancesRow, error)
	GetEmployeeByID(ctx context.Context, id int64) (GetEmployeeByIDRow, error)
	GetEmployeeDOB(ctx context.Context, id int64) (time.Time, error)
	GetEmployeeFromBranch(ctx context.Context, branchID int64) ([]GetEmployeeFromBranchRow, error)
	GetEmployeeSalaryDetails(ctx context.Context, employeeID int64) (GetEmployeeSalaryDetailsRow, error)
	GetExchangeRateAll(ctx context.Context) ([]GetExchangeRateAllRow, error)
	GetExhangeRateById(ctx context.Context, id int64) (GetExhangeRateByIdRow, error)
	GetLatestExchangeRate(ctx context.Context, currencyType string) ([]GetLatestExchangeRateRow, error)
	GetOneHrBranch(ctx context.Context, id int64) ([]HrBranch, error)
	GetOnePayroll(ctx context.Context, id int64) ([]GetOnePayrollRow, error)
	GetPayrolls(ctx context.Context, arg GetPayrollsParams) ([]HrPayroll, error)
	GetService(ctx context.Context, category string) ([]GetServiceRow, error)
	GetServices(ctx context.Context) ([]HrCreateService, error)
	GetTax(ctx context.Context) ([]GetTaxRow, error)
	GetTrainerAssingedCount(ctx context.Context, trainerID int64) (int64, error)
	GetTrainerEmp(ctx context.Context, employeeID int64) (GetTrainerEmpRow, error)
	GetTrainerEmpDataFromID(ctx context.Context, employeeID int64) (GetTrainerEmpDataFromIDRow, error)
	GetVisaFile(ctx context.Context, employeeID int64) (string, error)
	SelectAllPresetWorkouts(ctx context.Context) ([]SelectAllPresetWorkoutsRow, error)
	SelectAllPresets(ctx context.Context) ([]SelectAllPresetsRow, error)
	SelectAllSessionWorkouts(ctx context.Context) ([]SelectAllSessionWorkoutsRow, error)
	SelectAllSessions(ctx context.Context) ([]SelectAllSessionsRow, error)
	SelectHrAdmin(ctx context.Context, arg SelectHrAdminParams) ([]SelectHrAdminRow, error)
	SelectOneHrAdmin(ctx context.Context, id int64) (HrAdmin, error)
	SelectPreset(ctx context.Context, id int64) (SelectPresetRow, error)
	SelectPresetByname(ctx context.Context, name string) ([]SelectPresetBynameRow, error)
	SelectSession(ctx context.Context, id int64) (SelectSessionRow, error)
	SelectSessionWorkout(ctx context.Context, id int64) (SelectSessionWorkoutRow, error)
	SelectpresetSessionAll(ctx context.Context) ([]SelectpresetSessionAllRow, error)
	SuspendedHrAdmin(ctx context.Context, arg SuspendedHrAdminParams) error
	UpdateAllowance(ctx context.Context, arg UpdateAllowanceParams) error
	UpdateEmpAccessiability(ctx context.Context, arg UpdateEmpAccessiabilityParams) error
	UpdateEmpAllowances(ctx context.Context, arg UpdateEmpAllowancesParams) error
	UpdateEmpBankDetails(ctx context.Context, arg UpdateEmpBankDetailsParams) error
	UpdateEmpBenifits(ctx context.Context, arg UpdateEmpBenifitsParams) error
	UpdateEmpCertificates(ctx context.Context, arg UpdateEmpCertificatesParams) error
	UpdateEmpEmergencyDetails(ctx context.Context, arg UpdateEmpEmergencyDetailsParams) error
	UpdateEmpExpatriate(ctx context.Context, arg UpdateEmpExpatriateParams) error
	UpdateEmpSalary(ctx context.Context, arg UpdateEmpSalaryParams) error
	UpdateEmpStatus(ctx context.Context, arg UpdateEmpStatusParams) error
	UpdateEmpUser(ctx context.Context, arg UpdateEmpUserParams) error
	UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) error
	UpdateFileSubmit(ctx context.Context, arg UpdateFileSubmitParams) error
	UpdateHrAdmin(ctx context.Context, arg UpdateHrAdminParams) error
	UpdatePayroll(ctx context.Context, arg UpdatePayrollParams) error
	UpdatePayrollAllowance(ctx context.Context, arg UpdatePayrollAllowanceParams) error
	UpdatePreset(ctx context.Context, arg UpdatePresetParams) error
	UpdatePresetSession(ctx context.Context, arg UpdatePresetSessionParams) error
	UpdatePresetWorkout(ctx context.Context, arg UpdatePresetWorkoutParams) error
	UpdateService(ctx context.Context, arg UpdateServiceParams) error
	UpdateSessionWorkout(ctx context.Context, arg UpdateSessionWorkoutParams) error
	UpdateTax(ctx context.Context, arg UpdateTaxParams) error
	UpdateTrainerCommission(ctx context.Context, arg UpdateTrainerCommissionParams) error
}

var _ Querier = (*Queries)(nil)
